=== delwinmachan/productivity-manager/exam/exam.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<element name="company">
<complexType>
<sequence>
<element name="employee" maxOccurs="4">
<complexType>
<sequence>
<element name="Emp-name" type="string"></element>
<element name="Emp-age" type="integer"></element>
<element name="Emp-salary">
<simpleType>
<restriction base="integer">
<maxInclusive value="200000"></maxInclusive>
<minInclusive value="50000"></minInclusive>
</restriction>
</simpleType>
</element>
<element name="Emp-emailid" type="string"></element>
<element name="Emp-phonenum" type="integer"></element>
<element name="Emp-designation" type="string"></element>
</sequence>
<attribute name="aid" type="ID" use="required"></attribute>
</complexType>
</element>
</sequence>
</complexType>
</element>
</schema>

=== delwinmachan/productivity-manager/exam/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="exam.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exam.xsd">
  <employee aid="a1">
    <Emp-name>DELWIN THOMAS</Emp-name>
    <Emp-age>51</Emp-age>
    <Emp-salary>100000</Emp-salary>
    <Emp-emailid>delwintom@gmail.com</Emp-emailid>
    <Emp-phonenum>9526776443</Emp-phonenum>
    <Emp-designation>team leader</Emp-designation>
  </employee>
   <employee aid="a2">
    <Emp-name>ashna</Emp-name>
    <Emp-age>45</Emp-age>
    <Emp-salary>100900</Emp-salary>
    <Emp-emailid>ashna@gmail.com</Emp-emailid>
    <Emp-phonenum>9526776003</Emp-phonenum>
    <Emp-designation>developer</Emp-designation>
  </employee>
  <employee aid="a3">
    <Emp-name>seban</Emp-name>
    <Emp-age>20</Emp-age>
    <Emp-salary>100900</Emp-salary>
    <Emp-emailid>seban@gmail.com</Emp-emailid>
    <Emp-phonenum>9526776003</Emp-phonenum>
    <Emp-designation>developer</Emp-designation>
  </employee>
  
</company>
